export const SORT_GOODS = "content/SORT_GOODS"
export const SHOW_ALL = "content/SHOW_ALL"
export const ADD_TO_CART = "ADD_TO_CART"
export const REMOVE_FROM_CART = "REMOVE_FROM_CART"
export const SET_PCS = "SET_PCS"
